In [1]:
from dbts_model import DBSTransformerModel
from dbt_model import DBTransformerModel
from utils import generate_square_subsequent_mask
import torch

In [2]:
msk = generate_square_subsequent_mask(10)
msk[:3, :3]

tensor([[0., -inf, -inf],
        [0., 0., -inf],
        [0., 0., 0.]])

In [3]:
model_s = DBSTransformerModel(10, 1, 256, 1, 0.0, 2, 3e-4, 2, 2)
model_s.eval()
model = DBTransformerModel(10, 256, 256, 1, 0.0, 2, 3e-4)
model.eval()
""


''

In [4]:

import numpy as np


def repet(model):
    for i in range(10):
        ins = torch.tensor([[2, 1, 3, 7], [2, 1, 3, 2]])
        res = model.predict_step(ins)
        res2 = model.predict_step(ins)
        assert torch.all(res == res2)
    return res

# repet(model)
repet(model_s)

torch.Size([16, 512])


Exception: ok

In [ ]:
ins = torch.tensor([[2, 1, 3, 7]])
ins2 = torch.tensor([[2, 1, 3, 7, 8]])
res = model_s.predict_step(ins)
res2 = model_s.predict_step(ins2)

res, res2

(tensor([[3, 0, 1, 2]]), tensor([[3, 0, 1, 2, 0]]))

In [ ]:

ins = torch.tensor([[2, 1, 3, 7]])
res = model.predict_step(ins)
res2 = model.predict_step(ins)
res, res2

(tensor([[8, 4, 7, 3]]), tensor([[8, 4, 7, 3]]))