In [1]:
from dbts_model import DBSTransformerModel
from dbt_model import DBTransformerModel
from utils import generate_square_subsequent_mask
import torch

In [2]:
model_s = DBSTransformerModel(10, 2, 256, 1, 0.0, 1, 3e-4, 2, 2)
model_s.eval()
model = DBTransformerModel(10, 256, 256, 1, 0.0, 2, 3e-4)
model.eval()
""


''

In [4]:


def repet(model):
    for i in range(10):
        ins = torch.tensor([[9, 5], [5, 6]])
        # ins = torch.tensor([[9], [5]])
        res = model.predict_step(ins)
        res2 = model.predict_step(ins)
        assert torch.all(res == res2)
    return res

# repet(model)
repet(model_s)

tensor([[[ 0.4531, -0.3681,  0.7912, -0.1588,  0.0886,  0.5602, -0.6896,
           0.5103, -0.4330, -1.0034],
         [ 0.4531, -0.3681,  0.7912, -0.1588,  0.0886,  0.5602, -0.6896,
           0.5103, -0.4330, -1.0034]],

        [[ 0.4531, -0.3681,  0.7912, -0.1588,  0.0886,  0.5602, -0.6896,
           0.5103, -0.4330, -1.0034],
         [ 0.4531, -0.3681,  0.7912, -0.1588,  0.0886,  0.5602, -0.6896,
           0.5103, -0.4330, -1.0034]]], grad_fn=<ViewBackward0>)
tensor([[[ 0.4531, -0.3681,  0.7912, -0.1588,  0.0886,  0.5602, -0.6896,
           0.5103, -0.4330, -1.0034],
         [ 0.4531, -0.3681,  0.7912, -0.1588,  0.0886,  0.5602, -0.6896,
           0.5103, -0.4330, -1.0034]],

        [[ 0.4531, -0.3681,  0.7912, -0.1588,  0.0886,  0.5602, -0.6896,
           0.5103, -0.4330, -1.0034],
         [ 0.4531, -0.3681,  0.7912, -0.1588,  0.0886,  0.5602, -0.6896,
           0.5103, -0.4330, -1.0034]]], grad_fn=<ViewBackward0>)
tensor([[[ 0.4531, -0.3681,  0.7912, -0.1588,  0.0886,

tensor([[2, 2],
        [2, 2]])

In [ ]:


def repet(model):
    for i in range(10):
        # ins = torch.tensor([[9, 5]])
        ins = torch.tensor([[9, 5], [9, 5]])
        res = model.predict_step(ins)
        res2 = model.predict_step(ins)
        assert torch.all(res == res2)
    return res

# repet(model)
repet(model_s)

tensor([[9, 9],
        [9, 9]])

In [ ]:
(torch.ones([1, 2, 1]) @ torch.ones([4, 1]).T).shape

torch.Size([1, 2, 4])

In [ ]:
(torch.ones([1, 4, 1, 1]) @ torch.ones([1, 4, 1, 2])).shape

torch.Size([1, 4, 1, 2])

In [ ]:
ins = torch.tensor([[2, 1, 3, 7]])
ins2 = torch.tensor([[2, 1, 3, 7, 8]])
res = model_s.predict_step(ins)
res2 = model_s.predict_step(ins2)

res, res2

(tensor([[9, 9, 9, 9]]), tensor([[9, 9, 9, 9, 5]]))

In [ ]:
t = torch.tensor([[-0.1374],
        [-0.2049],
        [-0.1374],
        [-0.2049],
        [-0.1374],
        [-0.2049],
        [-0.1374],
        [-0.2049]])

In [ ]:
torch.ones([1, 2])

tensor([[1., 1.]])

In [ ]:
torch.ones([1, 2]) @ torch.ones([2, 8]).T

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x2 and 8x2)

In [ ]:
torch.ones([1, 2]) @ torch.ones([8, 2]).T

tensor([[2., 2., 2., 2., 2., 2., 2., 2.]])